# Regions are areas in your game that you travel to.
from typing import TYPE_CHECKING

neon_white_regions = [
    "Movement",
    "Pummel",
    "Gunner",
    "Cascade",
    "Elevate",
    "Bounce",
    "Purify",
    "Climb",
    "Fasttrack",
    "Glass Port",
    "Take Flight",
    "Godspeed",
    "Dasher",
    "Thrasher",
    "Outstretched",
    "Smackdown",
    "Catwalk",
    "Fastlane",
    "Distinguish",
    "Dancer",
    "Guardian",
    "Stomp",
    "Jumper",
    "Dash Tower",
    "Descent",
    "Driller",
    "Canals",
    "Sprint",
    "Mountain",
    "Superkinetic",
    "Arrival",
    "Forgotten City",
    "The Clocktower",
    "Fireball",
    "Ringer",
    "Cleaner",
    "Warehouse",
    "Boom",
    "Streets",
    "Steps",
    "Demolition",
    "Arcs",
    "Apartment",
    "Hanging Gardens",
    "Tangled",
    "Waterworks",
    "Killswitch",
    "Falling",
    "Shocker",
    "Bouquet",
    "Prepare",
    "Triptrack",
    "Race",
    "Bubble",
    "Shield",
    "Overlook",
    "Pop",
    "Minefield",
    "Mimic",
    "Trigger",
    "Greenhouse",
    "Sweep",
    "Fuse",
    "Heaven's Edge",
    "Zipline",
    "Swing",
    "Chute",
    "Crash",
    "Ascent",
    "Straightaway",
    "Firecracker",
    "Streak",
    "Mirror",
    "Escalation",
    "Bolt",
    "Godstreak",
    "Plunge",
    "Mayhem",
    "Barrage",
    "Estate",
    "Trapwire",
    "Ricochet",
    "Fortress",
    "Holy Ground",
    "The Third Temple",
    "Spree",
    "Breakthrough",
    "Glide",
    "Closer",
    "Hike",
    "Switch",
    "Access",
    "Congregation",
    "Sequence",
    "Marathon",
    "Sacrifice",
    "Absolution",
    "Elevate Traversal I",
    "Elevate Traversal II",
    "Purify Traversal",
    "Godspeed Traversal",
    "Stomp Traversal",
    "Fireball Traversal",
    "Dominion Traversal",
    "Book of Life Traversal",
    "Doghouse",
    "Choker",
    "Chain",
    "Hellevator",
    "Razor",
    "All Seeing Eye",
    "Resident Saw I",
    "Resident Saw II",
    "Sunset Flip Powerbomb",
    "Balloon Mountain",
    "Climbing Gym",
    "Fisherman Suplex",
    "STF",
    "Arena",
    "Attitude Adjustment",
    "Rocket"
]